test: &default

  # Credentials for REST APIs
  # client_id: ENV["paypal_client_id"]
  # client_secret: ENV["paypal_client_secret"]
  # EBPpzYRBO10cpMspzwbYOz-5T1Nh0Nkj6WtQz-LIA-txSKVgIA78LHjOyzkSJAV5I9Nysqc3yFfTXpJ0

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # AppID: APP-80W284485P519543T

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: spencerdnorman_api1.anglerdistrict.com
  password: 933B7RYXWJDH8ND7
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AGluHKX7dQdumjfb8XHJjbhyx72Y
  # # # With Certificate
  # # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
